global:
  scrape_interval: 5s
  scrape_timeout: 1s
  evaluation_interval: 15s

scrape_configs:
  - job_name: dev-push-gateway
    scrape_interval: 1s
    metrics_path: /metrics
    scheme: http
    static_configs:
    - targets: ['pushgateway:9091']
      labels:
        service: 'prom-pushgateway'